name: Create Folder Workflow
on: [push]

jobs:
  create-folder:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Create SAdeel Folder
        run: mkdir -p Shayan


